/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The sending half of a generation event channel.
 *
 * Generation backends obtain a sender from [`generation_channel`] and call
 * [`try_send`](Self::try_send), [`blocking_send`](Self::blocking_send), or
 * [`send_terminal`](Self::send_terminal) to push events to the consumer.
 *
 * Terminal events sent via [`send_terminal`] bypass the capacity check and
 * are therefore guaranteed to arrive even when the main event buffer is full.
 */
export declare class GenerationSender {
  /**
   * Try to send an event without blocking.
   *
   * Returns an error when the channel is full (the caller should retry
   * after the consumer drains) or closed (the consumer dropped the stream).
   */
  trySend(event: GenerationEvent): NapiResult<undefined>
  /**
   * Block the current thread until the event is sent.
   *
   * Fails when the consumer has dropped the stream.
   */
  blockingSend(event: GenerationEvent): NapiResult<undefined>
  /**
   * Send a terminal event through the unified queue, bypassing the
   * capacity limit.
   *
   * This always succeeds — the event will be delivered even if the
   * main event buffer is completely full. If the consumer has already
   * closed the stream, the event is still queued for draining.
   */
  sendTerminal(event: GenerationEvent): void
  /**
   * Attempt to send, returning an immediate `"Cancelled"` error when
   * the consumer has closed the stream.
   *
   * This is the preferred method for backends that want to avoid
   * unnecessary work once the consumer has disconnected.
   */
  trySendOrCancel(event: GenerationEvent): NapiResult<undefined>
  /** Check whether the consumer has dropped (closed) the stream. */
  isClosed(): boolean
  /** Maximum capacity the channel was created with. */
  capacity(): bigint
}

/**
 * The receiving half of a generation event channel.
 *
 * JS consumers call [`recv`](Self::recv) to block for the next event,
 * [`try_recv`](Self::try_recv) to poll without blocking, or
 * [`close`](Self::close) to signal that no more events are wanted.
 *
 * All events flow through a single unified queue so there is no wake-up race
 * between ordinary and terminal events.
 */
export declare class GenerationStream {
  /**
   * Block the current thread until the next event arrives, or the channel
   * is closed and drained (returns `None`).
   *
   * Terminal and ordinary events share a single queue so ordering is
   * preserved and there is no wake-up race.
   */
  recv(): GenerationEvent | null
  /**
   * Attempt to receive an event without blocking.
   *
   * Returns `None` when the queue is empty but still open, or closed
   * and drained.
   */
  tryRecv(): GenerationEvent | null
  /**
   * Close the stream — signals the sender via `is_closed()` that the
   * consumer has disconnected. Subsequent `try_send_or_cancel` calls on
   * the sender return `Cancelled`.
   *
   * Already-queued events (including terminal events sent afterwards via
   * [`send_terminal`](GenerationSender::send_terminal)) will still be
   * drained by [`recv`](Self::recv) before it returns `None`.
   */
  close(): void
  /** Returns `true` once [`close`](Self::close) has been called. */
  isClosed(): boolean
}

/**
 * Create a new bounded generation channel, returning the producer
 * ([`GenerationSender`]) and consumer ([`GenerationStream`]) pair.
 *
 * `capacity` controls the maximum number of buffered events before
 * [`try_send`](GenerationSender::try_send) returns an error. Defaults to 128.
 *
 * Terminal events sent via [`send_terminal`](GenerationSender::send_terminal)
 * bypass the capacity limit and are unaffected by this value.
 *
 * # Example (TypeScript)
 *
 * ```ts
 * const [sender, stream] = generationChannel(256);
 * // sender.send(...)  — from the backend
 * // stream.recv()      — from the consumer
 * ```
 */
export declare function generationChannel(capacity?: number | undefined | null): [GenerationSender, GenerationStream]

/**
 * Events emitted during a single generation run.
 *
 * Every run begins with `Started` and ends with `Done`, `Error(String)`,
 * `Cancelled`, or another terminal variant. Between bookends the stream
 * emits zero or more `Token`, `Chunk`, `Progress`, `Speed`, or `Warning`
 * events.
 */
export type GenerationEvent =
  | { type: 'Started' }
  | { type: 'Token', field0: number }
  | { type: 'Chunk', field0: string }
  | { type: 'Logits', field0: Array<number> }
  | { type: 'Progress', field0: number }
  | { type: 'Metrics', field0: string }
  | { type: 'Warning', field0: string }
  | { type: 'Error', field0: string }
  | { type: 'Done' }
  | { type: 'Cancelled' }

/**
 * Validate that a slice of events follows correct generation ordering rules:
 *
 * 1. `Started` comes first **if present** — no events may precede it.
 * 2. Tokens and streaming events occur only during *active* generation
 *    (after `Started`, before a terminal event).
 * 3. **Exactly one** terminal event exists (`Done`, `Error`, or `Cancelled`).
 * 4. No events appear after the terminal event.
 *
 * Returns `true` when the sequence satisfies all rules.
 */
export declare function validateEventSequence(events: Array<GenerationEvent>): boolean
export declare function add(a: number, b: number): number

export declare function arrayDataF32(handle: number, out: Float32Array): number

export declare function arrayEval(handle: number): void

export declare function arrayNbytes(handle: number): number

export declare function arrayShape(handle: number): Array<number>

export declare function arraySize(handle: number): number

/**
 * Compile a precompiled ComputeImage runtime artifact from a source model directory.
 * Outputs manifest.json, receipt.json, and execution-ordered segment files.
 */
export declare function compileImage(sourceDir: string, outputDir: string): string

export declare function createArrayF32(data: Float32Array, shape: Array<number>): number

export declare function createArrayRaw(data: Buffer, shape: Array<number>, dtypeId: number): number

export declare function createScalarF32(value: number): number

export declare function detectDefaultDevice(): any

export declare function drainArrays(): void

/**
 * Cancel an active generation by job ID.
 *
 * Bridge function — delegates to [`ComputeEngine::cancel_generation`].
 * Returns `{"cancelled": true}` on success or throws an napi error on
 * failure.  The real cancellation path requires a persistent engine
 * instance exposed as a napi external.
 */
export declare function engineCancelGeneration(imageHash: string, jobId: string): string

/**
 * Generate tokens from a compiled compute image using pre-tokenized input IDs.
 *
 * This is a bridge function for the napi layer.  The `input_ids` buffer
 * contains a sequence of little-endian `u32` token IDs (4 bytes each).
 *
 * Returns a JSON string with the generation job ID, e.g.:
 * ```json
 * {"jobId": "a1b2c3d4-...", "streamHandle": "<napi external placeholder>"}
 * ```
 *
 * The real streaming API goes through napi external — this bridge
 * demonstrates the interface shape and provides the job_id for polling.
 */
export declare function engineGenerate(imageHash: string, inputIds: Buffer, maxTokens: number): string

/** Install a model for the compute engine. */
export declare function engineInstallModel(imageDir: string, profile: string): string

export declare function freeArray(handle: number): void

export declare function gemma412BConfig(): string

export declare function gemmaForward(inputIds: Buffer, wh: string, kv: number): number

export declare function gemmaSampleGreedy(inputIds: Buffer, wh: string, kv: number): number

export declare function handleCount(): number

export declare function inspectSafetensors(path: string): string

export declare function loadSafetensors(path: string): string

export declare function matmul(a: number, b: number): number

/** Returns MLX Metal active memory in bytes, or 0 if unavailable. */
export declare function mlxActiveMemory(): number

/** Clear the MLX Metal allocator cache. Returns bytes freed. */
export declare function mlxClearCache(): number

export declare function multiply(a: number, b: number): number

/** Return the native dependency identity and capability report. */
export declare function nativeCapabilityReport(): string

export declare function parseConfigOnly(configPath: string): string

export declare function readCompiledImage(imageDir: string): string

/**
 * Execute the full 48-layer model from a compiled ComputeImage.
 * Returns the next token ID directly — no logits cross the FFI boundary.
 */
export declare function runFullModelFromImage(imageDir: string, inputIds: Buffer): number

export declare function validateFromMetadata(configPath: string, shardJsons: string): string

export declare function verifyCompiledImage(imageDir: string): string
